apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-ci-cd
spec:
  replicas: 2
  selector: 
    matchLabels:
      app: kubernetes-ci-cd
  template:
    metadata:
      labels:
        app: kubernetes-ci-cd
    spec:
      containers:
        - name: kubernetes-ci-cd
          image: afifmoetezdocker/kubernetes-ci-cd
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
            
